bootswatch: flatly

slogan: "聰明的輸入法懂我心意"

menu:
  - title: 下載
    url: download
    icon: "fa fa-download"
  - title: 文檔
    url: docs
    icon: "fa fa-question-circle"
  - title: 代碼
    url: code
    icon: "fa fa-code"
  - title: 捐贈
    url: donate
    icon: "fa fa-heart"
  - title: 網誌
    url: archives
    intro: "全部文章"
    icon: "fa fa-book"
#  - title: 分類
#    url: categories
#    intro: "所有分類"
#    icon: "fa fa-folder"
#  - title: 標籤
#    url: tags
#    intro: "所有標籤"
#    icon: "fa fa-tags"

links:
  - title: Rime Wiki
    url: https://github.com/rime/home/wiki
    icon: "fa fa-github"
  - title: Rime on Github
    url: https://github.com/rime
    intro: "Rime's Github repository."
    icon: "fa fa-github"
  - title: "佛振 @ Github"
    url: http://www.github.com/lotem
    intro: "Rime 開發者佛振"
    icon: "fa fa-github"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: true
fancybox: true
favicon: favicon.png
google_analytics:
